### ISSUE TITLE
Scala 2.13 support

### ISSUE THREAD

**Issue by otrosien** [lhotari/akka-http-health#3]
Hey Lari,

we're still using akka-http-health in some of our projects. Do you mind releasing a version with scala 2.13 support? Also akka-http 10.1 would be awesome.

**Comment by gregghz** [comment]
https://github.com/lhotari/akka-http-health/pull/4

**Comment by lhotari** [comment]
Fixed by #4 . I have released 1.0.9 version with those changes. Currently in bintray https://bintray.com/lhotari/releases/akka-http-health/1.0.9#files/io/github/lhotari and will be available in Maven central at https://repo1.maven.org/maven2/io/github/lhotari/akka-http-health_2.13 once it has been synchronized.

**Comment by lhotari** [comment]
Maven central sync from Bintray to Sonatype OSS hadn't completed successfully and I had to manually fix the issues. Bintray hadn't signed all of the files and that's why the sync had failed. It's now successfully completed and files should appear also in Maven central in a few hours. The 1.0.9 release is already available in Jcenter besides Bintray.
